import { City } from 'types';

export const cities: City[] = [
  { id: 1, name: "Tirana", ctry_code: "AL" },
  { id: 2, name: "Sofia", ctry_code: "BG" },
  { id: 3, name: "Plovdiv", ctry_code: "BG" },
  { id: 4, name: "Varna", ctry_code: "BG" },
  { id: 5, name: "Haskovo", ctry_code: "BG" },
  { id: 6, name: "Stara Zagora", ctry_code: "BG" },
  { id: 7, name: "Zagreb", ctry_code: "HR" },
  { id: 8, name: "Zadar", ctry_code: "HR" },
  { id: 9, name: "Dubrovnik", ctry_code: "HR" },
  { id: 10, name: "Copenhagen", ctry_code: "DK" },
  { id: 11, name: "Aarhus", ctry_code: "DK" },
  { id: 12, name: "Aalborg", ctry_code: "DK" },
  { id: 13, name: "Aalborg", ctry_code: "DK" },
  { id: 14, name: "Paris", ctry_code: "FR" },
  { id: 15, name: "Lyon", ctry_code: "FR" },
  { id: 16, name: "Nice", ctry_code: "FR" },
  { id: 17, name: "Strasbourg", ctry_code: "FR" },
  { id: 18, name: "Toulouse", ctry_code: "FR" },
  { id: 19, name: "Berlin", ctry_code: "DE" },
  { id: 20, name: "Munich", ctry_code: "DE" },
  { id: 21, name: "Hamburg", ctry_code: "DE" },
  { id: 22, name: "Dusseldorf", ctry_code: "DE" },
  { id: 23, name: "Stuttgart", ctry_code: "DE" },
  { id: 24, name: "Budapest", ctry_code: "HU" },
  { id: 25, name: "Debrecen", ctry_code: "HU" },
  { id: 26, name: "Szeged", ctry_code: "HU" },
  { id: 27, name: "Amsterdam", ctry_code: "NL" },
  { id: 28, name: "Rotterdam", ctry_code: "NL" },
  { id: 29, name: "Madrid", ctry_code: "ES" },
  { id: 30, name: "Barcelona", ctry_code: "ES" },
  { id: 31, name: "Valencia", ctry_code: "ES" },
  { id: 32, name: "Stockholm", ctry_code: "SE" },
  { id: 33, name: "Gothenburg", ctry_code: "SE" },
  { id: 34, name: "Malmo", ctry_code: "SE" },
];